version: "3.8"

services:
  openwebrx:
    image: jketterl/openwebrx:stable
    container_name: openwebrx
    restart: unless-stopped

    ports:
      - "8073:8073"

    devices:
      - /dev/bus/usb:/dev/bus/usb

    volumes:
      - ./data:/var/lib/openwebrx   # 🔥 aquí está la clave

    environment:
      - TZ=Europe/Madrid
